AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: jcloudify-api - Computation and API

Globals:
  Function:
    CodeUri: .
    Runtime: java21
    Tracing: Active
    Architectures:
      - arm64
    EventInvokeConfig:
      MaximumRetryAttempts: 0
    AutoPublishAlias: live
    SnapStart:
      ApplyOn: PublishedVersions
    VpcConfig:
      SecurityGroupIds:
        - !Sub '{{resolve:ssm:/jcloudify-api/sg/id}}'
      SubnetIds:
        - !Sub '{{resolve:ssm:/jcloudify-api/private/subnet1/id}}'
        - !Sub '{{resolve:ssm:/jcloudify-api/private/subnet2/id}}'
    Environment:
      Variables:
        ENV: !Ref Env
        AWS_S3_BUCKET: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/s3/bucket-name}}'
        AWS_SES_SOURCE: noreply@nowhere.com
        AWS_EVENTBRIDGE_BUS: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/eventbridge/bus-name}}'
        AWS_EVENT_STACK_1_SQS_QUEUE_URL: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/1/sqs/mailbox-queue-url}}'
        AWS_EVENT_STACK_2_SQS_QUEUE_URL: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/2/sqs/mailbox-queue-url}}'
        
        SPRING_DATASOURCE_URL: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/db/url}}'
        SPRING_DATASOURCE_USERNAME: !Sub '{{resolve:ssm:/jcloudify/${Env}/db/user/username}}'
        SPRING_DATASOURCE_PASSWORD: !Sub '{{resolve:ssm:/jcloudify/${Env}/db/user/password}}'
        GITHUB_CLIENT_ID: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/github/client/id}}'
        GITHUB_CLIENT_SECRET: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/github/client/secret}}'
        GITHUB_REDIRECT_URI: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/github/redirect/uri}}'
        GITHUB_TOKEN_URL: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/github/token/url}}'
        

Parameters:
  Env:
    Type: String

Resources:
  FrontalServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - "*~1*"

  FrontalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.jcloudify.app.ApiEventHandler::handleRequest
      MemorySize: 2048
      Timeout: 30
      Role: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/execution/role-arn}}'
      
      Events:
        ApiCall:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: FrontalServerlessRestApi

  WorkerFunction1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.jcloudify.app.MailboxEventHandler::handleRequest
      MemorySize: 1024
      Timeout: 600 #note(sqs-visibility)
      Role: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/execution/role-arn}}'
      
      Events:
        AllEvents:
          Type: SQS
          Properties:
            Queue: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/1/sqs/mailbox-queue-arn}}'
            BatchSize: 5

  WorkerFunction2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.jcloudify.app.MailboxEventHandler::handleRequest
      MemorySize: 1024
      Timeout: 600 #note(sqs-visibility)
      Role: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/execution/role-arn}}'
      
      Events:
        AllEvents:
          Type: SQS
          Properties:
            Queue: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/2/sqs/mailbox-queue-arn}}'
            BatchSize: 5

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

  ApiUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /jcloudify-api/, !Ref Env, /api/url ] ]
      Type: String
      Value: !Sub "https://${FrontalServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !GetAtt ApiUrlSSM.Value
