AWSTemplateFormatVersion: "2010-09-09"
Description: jcloudify-app-deployer - Event

Parameters:
  Env:
    Type: String

Resources:
  MailboxQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ['' , [!Ref Env , -jcloudify-app-deployer-api]]
      VisibilityTimeout: 901 #note(sqs-visibility): DeployerFunctionTimeout + 1
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5
      SqsManagedSseEnabled: false

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:  !Join ['' , [!Ref Env , -jcloudify-app-deployer-dl]]
      SqsManagedSseEnabled: false

  MailboxQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MailboxQueue
      PolicyDocument:
        Version: "2008-10-17"
        Id: "MailboxQueue_Policy"
        Statement:
          - Action:
              - "SQS:*"
            Effect: "Allow"
            Resource: !GetAtt MailboxQueue.Arn
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
          - Action:
              - "SQS:SendMessage"
            Effect: "Allow"
            Resource: !GetAtt MailboxQueue.Arn
            Principal:
              Service:
                - "events.amazonaws.com"
            Condition:
              ArnEquals:
                AWS:SourceArn: !GetAtt EventBridgeRule.Arn

  DeadLetterQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref DeadLetterQueue
      PolicyDocument:
        Version: "2008-10-17"
        Id: "DeadLetterQueue_Policy"
        Statement:
          - Action:
              - "SQS:*"
            Effect: "Allow"
            Resource: !GetAtt DeadLetterQueue.Arn
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root

  MailboxQueueSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['' , [/jcloudify-app-deployer/ , !Ref Env , /sqs/mailbox-queue-url]]
      Type: String
      Value: !Ref MailboxQueue

  MailboxQueueSSMArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['' , [/jcloudify-app-deployer/ , !Ref Env , /sqs/mailbox-queue-arn]]
      Type: String
      Value: !GetAtt MailboxQueue.Arn

  DeadLetterQueueSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['' , [/jcloudify-app-deployer/ , !Ref Env , /sqs/dead-letter-queue-url]]
      Type: String
      Value: !Ref DeadLetterQueue

  DeadLetterQueueArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '' , [ /jcloudify-app-deployer/ , !Ref Env , /sqs/dead-letter-queue-arn ] ]
      Type: String
      Value: !GetAtt DeadLetterQueue.Arn

  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Join ['', [!Ref Env, -jcloudify-app-deployer, -from-api-to-deployer]]
      EventBusName: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/eventbridge/bus-name}}'
      EventPattern:
        source:
          - app.jcloudify.app.deployer.event
      Targets:
        - Arn: !GetAtt MailboxQueue.Arn
          Id: !Join ['', [!Ref Env, -jcloudify-app-deployer, -mailbox]]

Outputs:
  MailboxQueueURL:
    Value: !Ref MailboxQueueSSM
  MailboxQueueArn:
    Value: !Ref MailboxQueueSSMArn
  DeadLetterQueueURL:
    Value: !Ref DeadLetterQueueSSM
  DeadLetterQueueArn:
    Value: !Ref DeadLetterQueueArnSSM
  EventBridgeBusName:
    Value: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/eventbridge/bus-name}}'
  EventBridgeArnName:
    Value: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/eventbridge/bus-arn}}'
