AWSTemplateFormatVersion: 2010-09-09
Description: jcloudify-api - Storage Postgres

Parameters:
  Env:
    Type: String
  DBName:
    Type: String
    Default: jcloudify-api-rds
  ProdDbClusterTimeout:
    Type: Number

Conditions:
  IsProdEnv: !Equals
    - !Ref Env
    - 'prod'

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Join [ '', [ Subnet group for jcloudify-api , !Ref Env ] ]
      DBSubnetGroupName: !Join [ '', [ jcloudify-api-, !Ref Env, -subnet-group ] ]
      SubnetIds:
        - !Sub '{{resolve:ssm:/jcloudify-api/private/subnet1/id}}'
        - !Sub '{{resolve:ssm:/jcloudify-api/private/subnet2/id}}'

  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      BackupRetentionPeriod: 35
      DatabaseName: !Join [ '', !Split [ '-', !Ref DBName ] ]
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeletionProtection: true
      Engine: aurora-postgresql
      EngineMode: serverless
      EngineVersion: 13.9 #Only postgresql version 13.9 and 11.9 supports Aurora serverless v1
      MasterUsername: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/db/username}}'
      MasterUserPassword: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/db/password}}'
      VpcSecurityGroupIds:
        - !Sub '{{resolve:ssm:/jcloudify-api/sg/id}}'
      ScalingConfiguration:
        MaxCapacity: 16
        MinCapacity: 2
        SecondsBeforeTimeout: 60
        AutoPause: false
        SecondsUntilAutoPause: !If [ IsProdEnv, 900, !Ref ProdDbClusterTimeout]
            


  DatabaseClusterSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /jcloudify-api/, !Ref Env, /db/url ] ]
      Type: String
      Value:
        Fn::Join:
          - ''
          - - jdbc:postgresql://
            - Fn::GetAtt:
                - DatabaseCluster
                - Endpoint.Address
            - ':'
            - Fn::GetAtt:
                - DatabaseCluster
                - Endpoint.Port
            - '/'
            - !Join [ '', !Split [ '-', !Ref DBName ] ]

  DatabaseClusterIdentifierSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /jcloudify-api/, !Ref Env, /db/identifier ] ]
      Type: String
      Value: !GetAtt DatabaseCluster.Endpoint.Address

Outputs:
  DatabaseClusterSSM:
    Value: !GetAtt DatabaseClusterSSM.Value