name: CD App Deployer Event

on:
  push:
    branches:
      - 'prod'
      - 'preprod'

  workflow_dispatch:

jobs:
  cd-app-deployer-event:
    if: github.ref_name == 'prod' || github.ref_name == 'preprod'

    runs-on: ubuntu-latest

    timeout-minutes: 10

    env:
      AWS_REGION: eu-west-3

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          secrets: ${{ toJSON(secrets) }}
          region: ${{ env.AWS_REGION }}

      - name: Deploy app deployer event stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ github.ref_name }}-app-deployer-event-jcloudify-api
          template: cf-stacks/app-deployer-event-stack.yml
          tags: "[ { \"Key\": \"app\", \"Value\": \"jcloudify-api\" },{ \"Key\": \"app\", \"Value\": \"jcloudify-app-deployer\" }, { \"Key\": \"env\", \"Value\": \"${{ github.ref_name }}\" }, { \"Key\": \"user:poja\", \"Value\": \"jcloudify-api\" } ]"
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
          parameter-overrides:
            "Env=${{ github.ref_name }}"
